FORMAT: 1A
HOST: https://oic1-olservices.uscom-east-1.oraclecloud.com:443/ic/api/integration/v1/flows/rest


# Banking API

This is a simple Banking API to perform banking transactions that are implemented using Oracle Integration Cloud for use with Lloyd's Banking Database


## Account List By Bank Code [/LW_MAP_ACCOUN_BY_BANK/1.0/accounts/{BankCode}]

+ Parameters

    + BankCode: ABC (string) - A BankCode for the accounts to retreive.

### List All Accounts By Bank Code [GET]
The Oracle Integration Cloud also shows the [metadata](https://oicdev-williams.uscom-central-1.oraclecloud.com/ic/api/integration/v1/flows/rest/LW_MAP_ACCOUN_BY_BANK/1.0/metadata) for this API.

+ Request
    + Headers

            Authorization: Basic bGxveWQuZS53aWxsaWFtc0BvcmFjbGUuY29tOkRjbUlBa2xqOSM=


+ Response 200 (application/json)

        [ 
            {
                "bankCode": "ABC",
                "accounts": [
                    {
                        "accountID": "ACCOUNT207",
                        "customerID": "C2000",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:12:46.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT208",
                        "customerID": "C2001",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:16:16.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT209",
                        "customerID": "C2001",
                        "acctType": "Checking",
                        "balance": 2300,
                        "lastActivityDate": "2018-02-27T17:17:16.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT303",
                        "customerID": "C2001",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:50:09.000-05:00"
                    }
                ]
            }
        ]

## Customer Accounts [/LW_MAP_ACCTS_CUSTOMER/1.0/accounts/{CustomerID}] 

+ Parameters

    + CustomerID: C2001 (string) - The customer id for the accounts to retreive.

### Get the Accounts for a Customer [GET]

This gets all the accounts that belong to a specific customer id. 
The Oracle Integration Cloud also shows the [metadata](https://oicdev-williams.uscom-central-1.oraclecloud.com/ic/api/integration/v1/flows/rest/LW_MAP_ACCTS_CUSTOMER/1.0/metadata) for this API.

+ Request
    + Headers

            Authorization: Basic bGxveWQuZS53aWxsaWFtc0BvcmFjbGUuY29tOkRjbUlBa2xqOSM=


+ Response 200 (application/json)
        
        [
            {  
                "customerID": "C2001",
                "accounts": 
                [
                    {
                        "accountID": "ACCOUNT208",
                        "bankCode": "ABC",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:16:16.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT209",
                        "bankCode": "ABC",
                        "acctType": "Checking",
                        "balance": 2300,
                        "lastActivityDate": "2018-02-27T17:17:16.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT303",
                        "bankCode": "ABC",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:50:09.000-05:00"
                    }
                ]
            }
        ]

## Get Activities By Account ID [/LW_MAP_ACCOUNT_ACTIVITI/1.0/activities/{AccountID}]

+ Parameters

    + AccountID: ACCOUNT208 (string) - The account id used to retreive activities

### Get Activities for an Account [GET]

This gets all the banking activity for the provided bacnk account id. 
dded ** TODO fix the response **

+ Request (application/json)
    + Headers

            Authorization: Basic bGxveWQuZS53aWxsaWFtc0BvcmFjbGUuY29tOkRjbUlBa2xqOSM=

+ Response 200 (application/json)

        [
            {  
                "accountID": "C2001",
                "accounts": 
                [
                    {
                        "accountID": "ACCOUNT208",
                        "bankCode": "ABC",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:16:16.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT209",
                        "bankCode": "ABC",
                        "acctType": "Checking",
                        "balance": 2300,
                        "lastActivityDate": "2018-02-27T17:17:16.000-05:00"
                    },
                    {
                        "accountID": "ACCOUNT303",
                        "bankCode": "ABC",
                        "acctType": "Checking",
                        "balance": 500,
                        "lastActivityDate": "2018-02-07T17:50:09.000-05:00"
                    }
                ]
            }
        ]


## Open Account [/LW_OPEN_ACCOUNT/1.0/account]

### Open a New Bank Account [POST]

You may create a bank account using this action. It takes a JSON
object containing the bank account and first deposit information and returns the status of the account creation request.

+ Request (application/json)
    + Headers

            Authorization: Basic bGxveWQuZS53aWxsaWFtc0BvcmFjbGUuY29tOkRjbUlBa2xqOSM=

    + Body
        
                {
                  "accountID": "ACCOUNT3500",
                  "bankCode": "ABC",
                  "customerID": "3",
                  "acctType": "Chequing",
                  "balance": 700.00
                }
           

+ Response 200 (application/json)
       
       + Attributes (Status Results)
        
## Perform Account Activity [/LW_PERFORM_ACCT_ACTIVITY/1.0/doaccountactivity]       

### Perform Account Activity [POST]

This API performs account activities like deposit and withdrawal

+ Request (application/json)
    + Headers

            Authorization: Basic bGxveWQuZS53aWxsaWFtc0BvcmFjbGUuY29tOkRjbUlBa2xqOSM=

    + Body
        
                {    
                    "accountID": "ACCOUNT107",
                    "transactionType": "D",
                    "amount": 431.75
                }
       

+ Response 200 (application/json)
       
                {
                    "statusCode": 0,
                    "errorReason": "OK"
                }


# Data Structures

## Status Results (object)
+ statusCode: 0 (number)

    A number to represent the code for the result.

+ errorReason: OK (string) 
    
    A string to describe the result